class MyError(Exception):
    pass

try:
